verbatim:
  cabal-version: 2.2

name: cs202-compiler
version: 0.0.0.0
license: GPL-3.0-or-later

ghc-options:
  - -j
  - -O0
  - -threaded -rtsopts -with-rtsopts=-N

dependencies:
  - base
  - pretty-simple
  - process
  - directory
  - containers
  - parsec >= 3.1.13
  - random
  - text

library:
  source-dirs: common

executables:
  a1-compiler:
    main: Main.hs
    source-dirs: a1
    dependencies: cs202-compiler
  a2-compiler:
    main: Main.hs
    source-dirs: a2
    dependencies: cs202-compiler
  a3-compiler:
    main: Main.hs
    source-dirs: a3
    dependencies: cs202-compiler
